//
// This file has been autogenerated by goffi-gen. DO NOT EDIT IT MANUALLY!
//

export interface GetIn {
    key: string;
}

export interface GetOut {
    value: string;
}

export interface SetIn {
    key:   string;
    value: string;
}

export interface SetOut {
}

export interface UnsetIn {
    key: string;
}

export interface UnsetOut {
}

// Converts JSON strings to/from your types
// and asserts the results of JSON.parse at runtime
export class Convert {
    public static toGetIn(json: string): GetIn {
        return cast(JSON.parse(json), r("GetIn"));
    }

    public static getInToJson(value: GetIn): string {
        return JSON.stringify(uncast(value, r("GetIn")), null, 2);
    }

    public static toGetOut(json: string): GetOut {
        return cast(JSON.parse(json), r("GetOut"));
    }

    public static getOutToJson(value: GetOut): string {
        return JSON.stringify(uncast(value, r("GetOut")), null, 2);
    }

    public static toSetIn(json: string): SetIn {
        return cast(JSON.parse(json), r("SetIn"));
    }

    public static setInToJson(value: SetIn): string {
        return JSON.stringify(uncast(value, r("SetIn")), null, 2);
    }

    public static toSetOut(json: string): SetOut {
        return cast(JSON.parse(json), r("SetOut"));
    }

    public static setOutToJson(value: SetOut): string {
        return JSON.stringify(uncast(value, r("SetOut")), null, 2);
    }

    public static toUnsetIn(json: string): UnsetIn {
        return cast(JSON.parse(json), r("UnsetIn"));
    }

    public static unsetInToJson(value: UnsetIn): string {
        return JSON.stringify(uncast(value, r("UnsetIn")), null, 2);
    }

    public static toUnsetOut(json: string): UnsetOut {
        return cast(JSON.parse(json), r("UnsetOut"));
    }

    public static unsetOutToJson(value: UnsetOut): string {
        return JSON.stringify(uncast(value, r("UnsetOut")), null, 2);
    }
}

function invalidValue(typ: any, val: any, key: any = ''): never {
    if (key) {
        throw Error(`Invalid value for key "${key}". Expected type ${JSON.stringify(typ)} but got ${JSON.stringify(val)}`);
    }
    throw Error(`Invalid value ${JSON.stringify(val)} for type ${JSON.stringify(typ)}`, );
}

function jsonToJSProps(typ: any): any {
    if (typ.jsonToJS === undefined) {
        const map: any = {};
        typ.props.forEach((p: any) => map[p.json] = { key: p.js, typ: p.typ });
        typ.jsonToJS = map;
    }
    return typ.jsonToJS;
}

function jsToJSONProps(typ: any): any {
    if (typ.jsToJSON === undefined) {
        const map: any = {};
        typ.props.forEach((p: any) => map[p.js] = { key: p.json, typ: p.typ });
        typ.jsToJSON = map;
    }
    return typ.jsToJSON;
}

function transform(val: any, typ: any, getProps: any, key: any = ''): any {
    function transformPrimitive(typ: string, val: any): any {
        if (typeof typ === typeof val) return val;
        return invalidValue(typ, val, key);
    }

    function transformUnion(typs: any[], val: any): any {
        // val must validate against one typ in typs
        const l = typs.length;
        for (let i = 0; i < l; i++) {
            const typ = typs[i];
            try {
                return transform(val, typ, getProps);
            } catch (_) {}
        }
        return invalidValue(typs, val);
    }

    function transformEnum(cases: string[], val: any): any {
        if (cases.indexOf(val) !== -1) return val;
        return invalidValue(cases, val);
    }

    function transformArray(typ: any, val: any): any {
        // val must be an array with no invalid elements
        if (!Array.isArray(val)) return invalidValue("array", val);
        return val.map(el => transform(el, typ, getProps));
    }

    function transformDate(val: any): any {
        if (val === null) {
            return null;
        }
        const d = new Date(val);
        if (isNaN(d.valueOf())) {
            return invalidValue("Date", val);
        }
        return d;
    }

    function transformObject(props: { [k: string]: any }, additional: any, val: any): any {
        if (val === null || typeof val !== "object" || Array.isArray(val)) {
            return invalidValue("object", val);
        }
        const result: any = {};
        Object.getOwnPropertyNames(props).forEach(key => {
            const prop = props[key];
            const v = Object.prototype.hasOwnProperty.call(val, key) ? val[key] : undefined;
            result[prop.key] = transform(v, prop.typ, getProps, prop.key);
        });
        Object.getOwnPropertyNames(val).forEach(key => {
            if (!Object.prototype.hasOwnProperty.call(props, key)) {
                result[key] = transform(val[key], additional, getProps, key);
            }
        });
        return result;
    }

    if (typ === "any") return val;
    if (typ === null) {
        if (val === null) return val;
        return invalidValue(typ, val);
    }
    if (typ === false) return invalidValue(typ, val);
    while (typeof typ === "object" && typ.ref !== undefined) {
        typ = typeMap[typ.ref];
    }
    if (Array.isArray(typ)) return transformEnum(typ, val);
    if (typeof typ === "object") {
        return typ.hasOwnProperty("unionMembers") ? transformUnion(typ.unionMembers, val)
            : typ.hasOwnProperty("arrayItems")    ? transformArray(typ.arrayItems, val)
            : typ.hasOwnProperty("props")         ? transformObject(getProps(typ), typ.additional, val)
            : invalidValue(typ, val);
    }
    // Numbers can be parsed by Date but shouldn't be.
    if (typ === Date && typeof val !== "number") return transformDate(val);
    return transformPrimitive(typ, val);
}

function cast<T>(val: any, typ: any): T {
    return transform(val, typ, jsonToJSProps);
}

function uncast<T>(val: T, typ: any): any {
    return transform(val, typ, jsToJSONProps);
}

function a(typ: any) {
    return { arrayItems: typ };
}

function u(...typs: any[]) {
    return { unionMembers: typs };
}

function o(props: any[], additional: any) {
    return { props, additional };
}

function m(additional: any) {
    return { props: [], additional };
}

function r(name: string) {
    return { ref: name };
}

const typeMap: any = {
    "GetIn": o([
        { json: "key", js: "key", typ: "" },
    ], false),
    "GetOut": o([
        { json: "value", js: "value", typ: "" },
    ], false),
    "SetIn": o([
        { json: "key", js: "key", typ: "" },
        { json: "value", js: "value", typ: "" },
    ], false),
    "SetOut": o([
    ], false),
    "UnsetIn": o([
        { json: "key", js: "key", typ: "" },
    ], false),
    "UnsetOut": o([
    ], false),
};

import { callNativeFunction } from "../lib";
import { Convert as ErrorConvert } from "../error";

function get(args: GetIn): Promise<GetOut> {
  return new Promise((resolve, reject) => {
    const argsJsonStr = Convert.getInToJson(args);
    const resultJsonStr = callNativeFunction("config", "get", argsJsonStr);
    try {
      resolve(Convert.toGetOut(resultJsonStr));
    } catch {
      reject(ErrorConvert.toStakError(resultJsonStr));
    }
  });
}

function set(args: SetIn): Promise<SetOut> {
  return new Promise((resolve, reject) => {
    const argsJsonStr = Convert.setInToJson(args);
    const resultJsonStr = callNativeFunction("config", "set", argsJsonStr);
    try {
      resolve(Convert.toSetOut(resultJsonStr));
    } catch {
      reject(ErrorConvert.toStakError(resultJsonStr));
    }
  });
}

function unset(args: UnsetIn): Promise<UnsetOut> {
  return new Promise((resolve, reject) => {
    const argsJsonStr = Convert.unsetInToJson(args);
    const resultJsonStr = callNativeFunction("config", "unset", argsJsonStr);
    try {
      resolve(Convert.toUnsetOut(resultJsonStr));
    } catch {
      reject(ErrorConvert.toStakError(resultJsonStr));
    }
  });
}

export const config = {
  get,
  set,
  unset,
}