//
// This file has been autogenerated by goffi-gen. DO NOT EDIT IT MANUALLY!
//

export interface DeployIn {
    workingDirectory: string;
}

export interface DeployOut {
}

export interface LoginIn {
}

export interface LoginOut {
}

export interface RunIn {
    workingDirectory: string;
}

export interface RunOut {
}

import { callNativeFunction } from "../lib";

function deploy(args: DeployIn): Promise<DeployOut> {
  return callNativeFunction<DeployOut>("core", "deploy", args);
}

function login(args: LoginIn): Promise<LoginOut> {
  return callNativeFunction<LoginOut>("core", "login", args);
}

function run(args: RunIn): Promise<RunOut> {
  return callNativeFunction<RunOut>("core", "run", args);
}

export const core = {
  deploy,
  login,
  run,
}