//
// This file has been autogenerated by goffi-gen. DO NOT EDIT IT MANUALLY!
//

export interface LoginIn {
}

export interface LoginOut {
}

import { callNativeFunction } from "../lib";

function login(args: LoginIn): Promise<LoginOut> {
  return callNativeFunction<LoginOut>("core", "login", args);
}

export const core = {
  login,
}