// 
// This file has been autogenerated by goffi-gen. DO NOT EDIT IT MANUALLY!`,
//

const ffi = require("ffi-napi");
const os = require("os");

// determine platform (darwin, linux)
const platform = os.platform();

// determine CPU architecture (arm64, amd64)
var arch = os.arch();
if (arch == "x64") {
    arch = "amd64";
}

const libPath = `${__dirname}/../prebuilds/libstak-core-${platform}-${arch}`;

const nativeLib = ffi.Library(libPath, {
  Call: ["string", ["string", "string", "string"]],
});

export function callNativeFunction(pkg: string, method: string, args: string): string {
    return nativeLib.Call(pkg, method, args);
}
